### ISSUE TITLE
Define meaning on equals / hashcode for core objects

### ISSUE THREAD

**Issue by chrisflatley** [annot8/annot8-core-deprecated#4]
We need a specification so that two things (group) are equal if.

I've started this process but it should probably cover all objects. 

I suspect that a lot of things (GroupStoer) are purely instance based, not based on their content. But for some items (particularly potentially db items such as Annotation that is less clear).

We need to avoid different implemetnations of Annotation (etc) from behaving differently when put in a set. Perhaps a solution is actually to provide a package of collections which have the correct behaviour in - encouraging the developer to use AnnotationSet (extend Set<Annotation>) rather that HashSet<Annotation>

**Comment by jamesdbaker** [comment]
I think we should use equals() to compare the value of two objects (e.g. do two groups hold the same annotations, do two annotations have the same properties and point to the same part of the same Content). Instance comparison should be done through ==.

We could provide a base class (in default-impl or common?) which provides this functionality as it should only involve the functions defined in the interface and not need any other access (although we could allow it to be overridden so annotations (for instance) can provide more efficient implementations for their storage mechanism.

**Comment by chrisflatley** [comment]
Whist I don't disagree with the convention we have to note that that .equals() (on group and annotation) would be probably not useful.

```
Annotation a = store.getById(123);
Annotation a2 = store.edit(a).setProperty('extra','prop').save()
Annotation a3  = store.getById(123);
// a.equals(a2) == false
// a2.equals(a3) == true
// a3 != a2 && a2 != a1 (different instances)
// but a.getId() == a2.getId() == a3.getId()
Set<Annotation> set; 
set.add(a1); set.add(a2); set.add(a3);
set = [a1, a2]
```
Seems a bit surprising? (given all the same id underneath, etc)

In practical use (in a processor) I'd assume you'd probably what just a single copy in that set? But as I say we could have a specific AnnotationSet which had that id based logic. (the Group has that logic)

its worth considering that every time you put stuff in that set you'll check everything (props and all) against everything else. But its premature optimisation to worry about that maybe. If for groups we are just checking AnnotationRreference stuff (content&annotationId) then that's ok.

Re instance: As I think never want compare to two GroupStores we shouldn't override it. That would be extremely computation inefficient (you'd have to get everything from the db). Its just more code to worry about without a real use case.

It's a shame you can't define equals on the interface - hence why I ended up with the equalsReference type stuff.

**Comment by jamesdbaker** [comment]
I don't think that example is surprising, that is how I would imagine it to work. Two annotations with the same ID aren't necessarily equal as they could (and do above) refer to the same annotation at different points in time.

In fact, if trying to keep track of history that is exactly what you need because you want to compare two annotations from different points in time and find out whether they are equal (i.e. no change). 

I think having an AnnotationSet with our own defined behaviour is a better approach than meaning something different to convention for equals (which will break compatibility with third party libraries).

**Comment by chrisflatley** [comment]
Yes, I'm not disagreeing on the equals as such, just saying that its perhaps not what you might behave as people image when they come to actually code something. 

In the above example if you tried to add the members of that set into a group with roles 'r0', 'r1', 'r2',... you'll not get what you think you might (because you' have the 'same annotation' which two different roles). (the set.size() == 2 , but group.size() == 1).

Another contrived one:

```
for(annotation a : store.getAnnotations() ) {
  store.edit(a).setProperty('count','0').save()
  for(annotation b : store.getAnnotations() ) {
    if(a.equals(b)) {
      System.out.println('never called - a is an old version');
    }
  }
}
```
As long as we are consistent and clear (`use a.getId().equals(b.getId()`) or annotation references then its ok.

**Comment by chrisflatley** [comment]
I assume conclusion from aboe would be that the annotation.equals does not include class then (ie SimpleAnnotation and say MongoAnnotation would be considered equal if the interface stuff id,properties,type,bounds are equal)

**Comment by jamesdbaker** [comment]
Yes, I think that would be ok - as a developer, I guess you'll generally be thinking more about the content than the implementation behind the scenes.

**Comment by chrisflatley** [comment]
Closing - pending some 'reference implementation test' to ensure things are valid in whatever impleemtaiton I think our default-impl defines this
